---
apiVersion: v1
kind: Pod
metadata:
  name: tpu-testing
  annotations:
    tf-version.cloud-tpus.google.com: "2.12.0"
spec:
  containers:
  - name: notebook
    image: tensorflow/tensorflow:2.12.0
    command: ["/bin/sh", "-c"]
    args:
    - "sleep INFINITY"
    resources:
      requests:
        cpu: 1
        memory: 4Gi
      limits:
        cpu: 1
        memory: 4Gi
        cloud-tpus.google.com/v2: 8